services:
  streamlit:
    build:
      context: . 
      dockerfile: docker/Dockerfile 
    ports:
      - "8501:8501"
    volumes:
      - .:/app 
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=chatbot
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=chatbot_db
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}

  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
